version: "3.0"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-webserver:
    image: nginx:1.23.1-alpine
    container_name: nginx-webserver
    expose:
      - 80
    volumes:
      - ./src:/var/www/html
      - .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/data/logs/nginx:/var/log/nginx
    environment:
      - VIRTUAL_HOST=laravel9-pms.com
      - LETSENCRYPT_HOST=laravel9-pms.com
      - LETSENCRYPT_EMAIL=email@site1.com
    depends_on:
      - nginx-proxy
      - mysql
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    container_name: laravel_php-fpm
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - LETSENCRYPT_HOST=phpmyadmin-pms.com
      - LETSENCRYPT_EMAIL=email@site1.com
      - VIRTUAL_HOST=phpmyadmin-pms.com
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_VERBOSE=mysql
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - nginx-proxy
      - mysql
    expose:
      - 80

  workspace:
    build:
      context: .
      dockerfile: .docker/workspace/Dockerfile
    container_name: laravel_workspace
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    tty: true

volumes:
  vhost:
